version: '3.9'

services:
  build-python:
    image: b86b296766e3
    container_name: build-python
    ports:
      - "5000:80"
    environment:
      CIRCLECI_API_TOKEN: c5e93e7110c016233060503778e365c42b9d6fae0c59ed0259535d5781250f805dbc79894509253f
      CIRCLECI_RESOURCE_CLASS: build
    depends_on:
      - postgres

  test-python:
    image: b86b296766e3
    container_name: test-python
    ports:
      - "5001:80"
    environment:
      CIRCLECI_API_TOKEN: c5cbc7931eeb7d7414f31f4ea8e3f1b31e859c397e654ff7f038d082595b65559b8dbc1d566b19b1
      CIRCLECI_RESOURCE_CLASS: test
    depends_on:
      - postgres

  postgres:
    image: cimg/postgres:13.10
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data:
