version: 2.1
      
jobs:
  
  Docker-start:
    machine: true
    resource_class: viplaw-singh/ubuntu-22
    steps:
      
      # Start the Docker Compose services
      - run:
          name: Start Docker Compose
          command: |
             docker-compose up -d 

      # Wait for the services to be ready (e.g., PostgreSQL may take a few seconds to start)
      - run:
          name: Wait for services to be ready
          command: sleep 5

  build:
    machine: true
    resource_class: viplaw-singh/build
    environment:
          TEST_DATABASE_URL_1: postgresql://postgres@10.0.12.36/circle_test 
          POSTGRES_DB: circle_test
          POSTGRES_USER: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

    steps:
      - checkout
      - run: 
          name: "install dependencies and Build"
          command: |
            sudo apt-get update -y 
            sudo apt-get install -y python3
            sudo apt-get install -y python3-pip
            pip  install -r requirements/base.txt
      
      - run:
          name: "Run migration"
          command: |
            python3 manage.py migrate
            

      - run:
          name: Run tests
          command: |
            mkdir test-results
            TEST_FILES=$(circleci tests glob "**/test_*.py")
            echo "$TEST_FILES" | circleci tests run --command="xargs pytest -o junit_family=legacy --junitxml=test-results/junit.xml" --verbose --split-by=name       
            pytest $TEST_FILES

      - store_test_results:
         path: test-results  

  #wait_for_test_completion:
    #machine: true
    #resource_class: viplaw-singh/ubuntu-runner
    #steps:
      #- checkout
      #- run:
          #name: Wait for Completion
          #command: |
            #echo "lambda test completed"    
  test:
    machine: true
    resource_class: viplaw-singh/test
    environment:
          TEST_DATABASE_URL_1: postgresql://postgres@10.0.12.36/circle_test 
          POSTGRES_DB: circle_test
          POSTGRES_USER: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          
    steps:
      - checkout
      
      - run:
          name: "Run Test"
          command: |
            pip  install -r requirements/local.txt
            python3 -m pip install pytest
            mkdir test-results
            TEST_FILES=$(circleci tests glob "**/test_*.py")
            echo "$TEST_FILES" | circleci tests run --command="xargs pytest -o junit_family=legacy --junitxml=test-results/junit.xml" --verbose --split-by=name
            pytest --cov $TEST_FILES
     
      - store_test_results:
         path: test-results   
           

  Docker-down:
    machine: true
    resource_class: viplaw-singh/ubuntu-22
    steps:
     # Stop the Docker Compose services after the build is complete
      - run:
          name: Stop Docker Compose
          command: |
             docker-compose down
            

workflows:
  main:
    jobs:
      - Docker-start
      - build:
          requires:
            - Docker-start
      - test:
          requires:
            - Docker-start
      - Docker-down:
          requires:
             - build
             - test
