version: 2.1
orbs:
  python: circleci/python@1.1.0

jobs:    
  build:
    machine: true
    resource_class: viplaw-singh/ubuntu-machine
    steps:
      - checkout
      - run:
          name: "Run Test"
          command: |
            pytest
           
workflows:
  main:
    jobs:
      - build
          
