version: 2.1
      
jobs:
  build:
    machine: true
    resource_class: viplaw-singh/build
    environment:
          TEST_DATABASE_URL_1: postgresql://postgres@localhost/socialnetworkdb 
          POSTGRES_DB: socialnetworkdb
          POSTGRES_USER: demo
          POSTGRES_HOST: 10.0.12.36
    steps:
      - checkout
      - run: 
          name: "install dependencies and Build"
          command: |
            sudo apt-get update -y 
            sudo apt-get install -y python3
            sudo apt-get install -y python3-pip
            pip  install -r requirements/base.txt
      - run:
          name: Run tests
          command: |
            mkdir test-results
            TEST_FILES=$(circleci tests glob "**/test_*.py")
            echo "$TEST_FILES" | circleci tests run --command="xargs pytest -o junit_family=legacy --junitxml=test-results/junit.xml" 
      - run:
          name: "Run migration"
          command: |
            python3 manage.py migrate
            pytest $TEST_FILES

      - store_test_results:
         path: test-results  

  #wait_for_test_completion:
    #machine: true
    #resource_class: viplaw-singh/ubuntu-runner
    #steps:
      #- checkout
      #- run:
          #name: Wait for Completion
          #command: |
            #echo "lambda test completed"    
  test:
    machine: true
    resource_class: viplaw-singh/test
    environment:
          TEST_DATABASE_URL_1: postgresql://postgres@localhost/socialnetworkdb 
          POSTGRES_DB: socialnetworkdb
          POSTGRES_USER: demo
          POSTGRES_HOST: 10.0.12.36
    steps:
      - checkout
      
      - run:
          name: "Run Test"
          command: |
            mkdir test-results
            TEST_FILES=$(circleci tests glob "**/test_*.py")
            echo "$TEST_FILES" | circleci tests run --command="xargs pytest -o junit_family=legacy --junitxml=test-results/junit.xml" --verbose --split-by=filename
            pip  install -r requirements/local.txt
            python3 -m pip install pytest
            pytest --cov $TEST_FILES
     
      - store_test_results:
         path: test-results   
           
workflows:
  main:
    jobs:
      - build
      - test
          
      #- wait_for_test_completion
          #requires:
            #- install_dependencies
      #- build
          #requires:
            #- wait_for_test_completion
