version: 2.1
orbs:
  python: circleci/python@1.1.0
jobs:
  build:
    executor: python/default
    docker:
      - image: cimg/postgres:12.0
        environment:
          DB_NAME: socialnetworkdb
          DB_USER: demo
          DB_PASSWORD: password
          DB_HOST: localhost
          DB_PORT: 5432


    resource_class: medium
    steps:
      - checkout
      - run: 
          name: "install dependencies"
          command: |
            pip  install -r requirements/base.txt
            pip  install -r requirements/local.txt
     
      - run:
          name: "Run migration"
          command: |
            python manage.py migrate

      - run:
          name: "Run Test"
          command: |
            pytest
           
workflows:
  main:
    jobs:
      - build
