version: 2.1
orbs:
  python: circleci/python@1.1.0
executors:
  my-executor:
    docker:
      - image: cimg/python:3.9
      - image: cimg/postgres:14.0
        environment:
          TEST_DATABASE_URL_1: postgresql://postgres@localhost/socialnetworkdb 
          POSTGRES_DB: socialnetworkdb
          POSTGRES_USER: demo
      
jobs:
  executors: my-executor
  install_dependencies:
    machine: true
    resource_class: viplaw-singh/ubuntu-runner
    steps:
      - checkout
      - run: 
          name: "install dependencies"
          command: |
            #sudo apt-get update -y 
            #sudo apt-get install -y python3
            #sudo apt-get install -y python3-pip
            pip  install -r requirements/base.txt
            pip  install -r requirements/local.txt
     
      - run:
          name: "Run migration"
          command: |
            python3 manage.py migrate
            pytest
  
  #wait_for_test_completion:
    #machine: true
    #resource_class: viplaw-singh/ubuntu-runner
    #steps:
      #- checkout
      #- run:
          #name: Wait for Completion
          #command: |
            #echo "lambda test completed"    
  #build:
    #machine: true
    #resource_class: viplaw-singh/ubuntu-runner
    #steps:
      #- checkout
      #- run:
          #name: "Run Test"
          #command: |
            #python3 -m pip install pytest
            #pytest --cov
           
workflows:
  main:
    jobs:
      - install_dependencies
      #- wait_for_test_completion
          #requires:
            #- install_dependencies
      #- build
          #requires:
            #- wait_for_test_completion
