version: 2.1
      
jobs:
  build:
    machine: true
    resource_class: viplaw-singh/test
    environment:
          TEST_DATABASE_URL_1: postgresql://postgres@localhost/socialnetworkdb 
          POSTGRES_DB: socialnetworkdb
          POSTGRES_USER: demo
    steps:
      - checkout
      - run: 
          name: "install dependencies and Build"
          command: |
            sudo apt-get update -y 
            sudo apt-get install -y python3
            sudo apt-get install -y python3-pip
            pip  install -r requirements/base.txt
  
      - run:
          name: "Run migration"
          command: |
            python3 manage.py migrate
            pytest
  
  #wait_for_test_completion:
    #machine: true
    #resource_class: viplaw-singh/ubuntu-runner
    #steps:
      #- checkout
      #- run:
          #name: Wait for Completion
          #command: |
            #echo "lambda test completed"    
  test:
    machine: true
    resource_class: viplaw-singh/build
    steps:
      - checkout
      - run:
          name: "Run Test"
          command: |
            pip  install -r requirements/local.txt
            python3 -m pip install pytest
            pytest --cov
           
workflows:
  main:
    jobs:
      - build
      - test
      #- wait_for_test_completion
          #requires:
            #- install_dependencies
      #- build
          #requires:
            #- wait_for_test_completion
